all: part1 part2 part3 part4

part1: assign4p1.c nqueens_library.c
	gcc -g -o part1 assign4p1.c nqueens_library.c
part2: assign4p2.c nqueens_library.c
	gcc -g -o part2 assign4p2.c nqueens_library.c
part3: assign4p3.c nqueens_library.c
	gcc -g -o part3 assign4p3.c nqueens_library.c
part4: assign4p4.c nqueens_library.c
	gcc -g -o part4 assign4p4.c nqueens_library.c -lpthread

